# Generated by Django 4.2a1 on 2023-03-13 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('plan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user'),
        ),
    ]
