# Generated by Django 4.2a1 on 2023-05-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0002_alter_plan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
