# Generated by Django 4.2a1 on 2023-05-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0003_remove_plan_created_at_remove_plan_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='isChecked',
            new_name='is_checked',
        ),
    ]
